# Question no 1

In [1]:
import numpy as np

# Question no 2

In [2]:
import numpy as np

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Question no 3

In [4]:
import numpy as np 

In [5]:
v = np.arange(10,49)
print("All vectors from 10 to 49 are:\n",v)

All vectors from 10 to 49 are:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Question no 04

In [6]:
import numpy as np
v = np.arange(10,49)
print(v.shape)


(39,)


# Question no 5

In [7]:
import numpy as np
v = np.arange(10,49)
print(v.dtype)

int32


# Question no 6

# Question no 7

In [8]:
import numpy as np

In [9]:
v = np.arange(10,49)
print(v.ndim)

1


# Question no 8

In [10]:
import numpy as np

In [11]:
arr = np.ones((2,2), dtype=bool)
print(arr)

[[ True  True]
 [ True  True]]


# Question no 9

In [12]:
import numpy as np

In [13]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Question no 10

In [14]:
import numpy as np

In [15]:
arr3 = np.arange(27).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Question no 11

In [16]:
import numpy as np

In [17]:
arr = np.array([2,4,6,8,10,12,14,16])
arr_reversed = arr[::-1]
arr_reversed

array([16, 14, 12, 10,  8,  6,  4,  2])

# Question no 12

In [18]:
import numpy as np

In [19]:
x = np.zeros(10)
print(x)
print("Update the fifth value\n")
x[5]=1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update the fifth value

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


# Question no 13

In [20]:
import numpy as np

In [21]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question no 14

In [22]:
import numpy as np

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [24]:
x = arr.astype(float)
x

array([1., 2., 3., 4., 5.])

# Question no 15

In [25]:
import numpy as np

In [26]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr_result = np.multiply(arr1, arr2)
print(arr_result)

[[ 0.  8.  3.]
 [28. 10. 72.]]


# Question no 16

In [27]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comparison = arr1 == arr2
equal_arrays = comparison.all()
print(equal_arrays)

False


# Question no 17

In [28]:
import numpy as np

In [29]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2==1]

array([1, 3, 5, 7, 9])

# Question no 18

In [30]:
import numpy as np

In [31]:
a = np.array([0, 1,  2,  3,  4,  5,  6,  7,  8,  9]) 
 
odd_values = (a%2 == 1) 
a[odd_values] = -1 

In [32]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Question no 19

In [33]:
import numpy as np

In [34]:
a = np.arange(10)
print(a)
print('\n')
a[5]=12
a[6]=12
a[7]=12
a[8]=12
print("After updating of index 5,6,7,8\n\n")
print(a)

[0 1 2 3 4 5 6 7 8 9]


After updating of index 5,6,7,8


[ 0  1  2  3  4 12 12 12 12  9]


# Question no 20

In [35]:
import numpy as np

In [36]:
x = np.ones((5,5))
print(x)
print("\nPrint 1 on Borders and 0 in inside \n")
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Print 1 on Borders and 0 in inside 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Question no 21

In [37]:
import numpy as np

In [38]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
d = {5:12}
print(d)



{5: 12}


# Question no 22

In [39]:
import numpy as np

# Question no 23

# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
import numpy as np

In [41]:
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr[0]

0

# Question no 24

# Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [46]:
import numpy as np

In [47]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr[1,1]

4

# Question no 25

In [49]:
import numpy as np

In [51]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr[:-1,0:3]

array([[0, 1, 2],
       [3, 4, 5]])

# Question no 26

In [43]:
import numpy as np

In [44]:
arr = np.random.randint(100,size=(10,10))
print(arr)
print("\nMinimum and maximum values\n")
print(np.min(arr))
print(np.max(arr))

[[59 34 32 45 67 88 39 55 51 71]
 [69 52 73 26 61 34 38 60  8 43]
 [51 26 62 93 96 38 25 29 47 83]
 [51 31 71  0 11 24 57 15  7 88]
 [37 90 52 62 26 29 41 53 24  1]
 [59  4 54 87 46 17 71 42 14 18]
 [80 29 73 66 78 96 57 46 64 39]
 [74 62  0 66 79 82 72 47 32  9]
 [65 97 98 52 21  3 76 91  5 42]
 [42 67 14 90 41  0 46 61 75 53]]

Minimum and maximum values

0
98


# Question no 27

In [61]:
import numpy as np

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
R= np.intersect1d(a,b)
print(R)

[2 4]


# Question no 29

In [1]:
import numpy as np

In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
x = names!="Will"
print(x)
y = data[x]
print(y)

[ True  True False  True False  True  True]
[[-0.37702623 -0.63655406  0.39028231 -1.6020757 ]
 [ 0.04824577 -0.92559208  0.61149023  0.71881967]
 [ 0.69366545 -0.73633536  0.12374539  0.11882952]
 [ 0.10287409  0.76403568 -1.38596849  0.69191125]
 [ 1.03478629  0.36919208  0.20598513  0.93442123]]
