# Question# 1

In [1]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [2]:
print("Numpy 1D Arrray:")
print(arr)

Numpy 1D Arrray:
[0 1 2 3 4 5 6 7 8 9]


In [3]:

arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr_2d=np.reshape(arr, (2,5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question # 02

In [4]:
import numpy as np

In [5]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9],[1,1,1,1,1],[1,1,1,1,1]])

In [6]:
out_arr = np.vstack((arr))

In [7]:
out_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question # 03

In [8]:
import numpy as np

In [9]:
a = np.array((0,1,2,3,4,1,1,1,1,1))
b = np.array((5,6,7,8,9,1,1,1,1,1))
np.hstack((a,b))


array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

In [10]:
a = np.array([[0],[1],[2],[3],[4],[1],[1],[1],[1],[1]])
b = np.array([[5],[6],[7],[8],[9],[1],[1],[1],[1],[1]])

In [11]:
arr=np.hstack((a,b))
arr


array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

# Question # 04

In [12]:
import numpy as np

In [13]:
array2D = np.array([[0,1,2], [3,4,5], [6,7,8]])
# printing initial arrays 
print("Given array:\n",array2D)
# Using flatten()
res = array2D.flatten()

Given array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
print("Flattened array:\n ", res)

Flattened array:
  [0 1 2 3 4 5 6 7 8]


# Question # 05

In [15]:
import numpy as np
arr2D = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
# printing initial arrays 
print("Given array:\n",arr2D)
# Using flatten() to change dimension
res = arr2D.flatten()

Given array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
print("Flattened array:\n ", res)

Flattened array:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Question# 06

In [17]:
import numpy as np

In [19]:
arr = np.arange(15).reshape(-1,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Question 7

In [ ]:
import numpy as np

In [ ]:
x = np.random.random((5,5))
print("Original Array:")
print(x) 
arr_2d_square = np.square(x)
print(f'square array :\n{arr_2d_square}')

# Question # 08

In [ ]:
import numpy as np

In [ ]:
np.random.seed(456)

In [20]:
arr = np.random.randint(30,size=(5,6))
print(arr)
arr.mean()

[[10 26 13  1 21 11]
 [21  8 14  4 24 23]
 [ 2 19 24 27 11  4]
 [ 2  0  7 13  4 17]
 [ 6  0 10 16 27  3]]


12.266666666666667

# Question no 09

In [ ]:
import numpy as np

In [ ]:
np.random.seed(456)
arr = np.random.randint(30,size =(5,6))
print(arr)

In [21]:
np.std(arr)

8.71754297698357

# Question no 10

In [ ]:
import numpy as np

In [22]:
np.random.seed(456)
arr = np.random.randint(30,size =(5,6))
np.median(arr)

13.0

# Question no 11

In [23]:
import numpy as np

In [24]:
np.random.seed(456)
arr = np.random.randint(30,size=(5,6))
arr

array([[27,  5, 11, 25, 10, 15],
       [28, 14, 15, 26, 20, 13],
       [28, 13,  5, 28,  7, 17],
       [11,  8, 19, 13,  5,  2],
       [14, 20,  2,  2, 11,  8]])

In [25]:
arr.T

array([[27, 28, 28, 11, 14],
       [ 5, 14, 13,  8, 20],
       [11, 15,  5, 19,  2],
       [25, 26, 28, 13,  2],
       [10, 20,  7,  5, 11],
       [15, 13, 17,  2,  8]])

# Question no 12

In [26]:
import numpy as np

In [27]:
arr = np.arange(16).reshape(4,4)
print(arr)
np.diagonal(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

# Question no 13

In [28]:
import numpy as np

In [31]:
arr = np.arange(16).reshape(4,4)
print(arr)
np.linalg.det(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


0.0

# Question no 14

In [32]:
import numpy as np

In [33]:
arr = np.arange(10)
print(arr)
print(np.percentile(arr,5))
print(np.percentile(arr,95))

[0 1 2 3 4 5 6 7 8 9]
0.45
8.549999999999999


# Question no 15

In [34]:
import numpy as np

In [38]:
arr = np.array([[0,0,0],[2,4,6],[9,0,8],[8,7,6]])
arr

array([[0, 0, 0],
       [2, 4, 6],
       [9, 0, 8],
       [8, 7, 6]])

In [39]:
arr_with_nan = np.isnan(arr)

In [42]:
(arr_with_nan)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

#                     OR

In [43]:
import numpy as np
     
b = [[1,2,3],[np.nan,np.nan,2]] 
arr = np.array(b)

print(arr)
print(np.isnan(arr))

x = np.isnan(arr)

#replacing NaN values with 0
arr[x] = 0
print("After replacing NaN values:")
arr

[[ 1.  2.  3.]
 [nan nan  2.]]
[[False False False]
 [ True  True False]]
After replacing NaN values:


array([[1., 2., 3.],
       [0., 0., 2.]])